# Generated by Django 4.0.6 on 2022-09-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('depertment', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
