# Generated by Django 4.0.6 on 2022-09-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
