# Generated by Django 4.0.6 on 2022-09-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0009_alter_farmerinfo_usertype_alter_logininfo_usertype_and_more'),
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersellproduct',
            name='farmerName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fmiapp.farmerinfo'),
        ),
        migrations.AddField(
            model_name='farmersellproduct',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmersellproduct',
            name='productName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmersellproduct',
            name='qty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fmiapp.farmerinfo')),
            ],
        ),
        migrations.AddField(
            model_name='farmersellproduct',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farmerapp.profile'),
        ),
    ]
