# Generated by Django 4.0.6 on 2022-09-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0009_alter_farmerinfo_usertype_alter_logininfo_usertype_and_more'),
        ('farmerapp', '0002_farmersellproduct_farmername_farmersellproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='farmerName',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='fmiapp.farmerinfo'),
        ),
    ]
