# Generated by Django 4.0.6 on 2022-09-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchantapp', '0005_orderdetail_track_update'),
        ('farmerapp', '0004_remove_farmersellproduct_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderStatus', models.CharField(default='', max_length=100)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('orderId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='merchantapp.orderdetail')),
            ],
        ),
    ]
