# Generated by Django 4.0.6 on 2022-10-08 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0011_alter_farmerinfo_userid_alter_merchantinfo_userid'),
        ('farmerapp', '0036_alter_tracker_orderid_alter_tracker_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmersellproduct',
            name='farmerName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='fmiapp.farmerinfo'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 16, 27, 39, 830538)),
        ),
    ]
