# Generated by Django 4.0.6 on 2022-10-08 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0037_alter_farmersellproduct_farmername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 18, 38, 50, 938050)),
        ),
    ]
