# Generated by Django 4.1.3 on 2022-12-13 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0057_alter_tracker_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersellproduct',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 13, 15, 40, 2, 191111)),
        ),
    ]
