# Generated by Django 4.1.3 on 2022-12-13 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0058_farmersellproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersellproduct',
            name='prodImage',
            field=models.ImageField(default=' ', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracker',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 13, 16, 1, 8, 383954)),
        ),
    ]
