# Generated by Django 4.0.6 on 2022-09-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantapp', '0002_orderdetail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='merchantId',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='merchantName',
            field=models.CharField(default='', max_length=10),
        ),
    ]
