# Generated by Django 4.0.6 on 2022-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantapp', '0004_orderdetail_farmerid_orderdetail_farmername'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='track_update',
            field=models.CharField(default='Your Order has been placed', max_length=600),
        ),
    ]
