# Generated by Django 4.0.6 on 2022-09-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantapp', '0005_orderdetail_track_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='productid',
            field=models.CharField(default='', max_length=150),
        ),
    ]
