# Generated by Django 4.0.6 on 2022-09-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0004_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='usertype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
