# Generated by Django 4.0.6 on 2022-09-18 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0009_alter_farmerinfo_usertype_alter_logininfo_usertype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantinfo',
            name='emailaddress',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='regdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='regdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
