# Generated by Django 4.0.6 on 2022-09-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0010_remove_merchantinfo_emailaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerinfo',
            name='userid',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='userid',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
